using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class BcAcampantes
    {
        public int AcaCod { get; set; }
        public string AcaNom { get; set; }
        public int? EscCod { get; set; }
        public DateTime? AcaNas { get; set; }
        public int? BcatCod { get; set; }
        public decimal? FamCod { get; set; }
        public string AcaSex { get; set; }
        public decimal? MaeCod { get; set; }
        public string AcaMail { get; set; }
        public decimal? PaiCod { get; set; }
        public string AcaSer { get; set; }
        public string AcaGra { get; set; }
        public string AcaAti { get; set; }
        public int? AcaOut { get; set; }
        public string AcaMor { get; set; }
        public string AcaMorNom { get; set; }
        public string AcaMorPar { get; set; }
        public string AcaMorMail { get; set; }
        public DateTime? AcaCad { get; set; }
        public int? UsuCod { get; set; }
        public DateTime? AcaAtu { get; set; }
        public string AcaFoto { get; set; }
        public string AcaCel { get; set; }
        public string AcaMorTel { get; set; }
        public string AcaDep { get; set; }
        public int? AcaAno { get; set; }
        public string AcaCam { get; set; }
        public string AcaObs { get; set; }
        public string AcaReg { get; set; }
        public string AcaOem { get; set; }
        public int? UsuCad { get; set; }
        public int? AcaMailChe { get; set; }
        public string AcaSen { get; set; }
        public int? AcaArtpir { get; set; }
        public int? AcaArtpin { get; set; }
        public int? AcaArtmag { get; set; }
        public int? AcaArtsap { get; set; }
        public int? AcaArttea { get; set; }
        public int? AcaArtaxe { get; set; }
        public int? AcaArtdes { get; set; }
        public int? AcaArtbal { get; set; }
        public int? AcaArtmal { get; set; }
        public int? AcaArtdan { get; set; }
        public string AcaArtout { get; set; }
        public int? AcaEsptre { get; set; }
        public int? AcaEspmus { get; set; }
        public int? AcaMusvio { get; set; }
        public int? AcaEspalp { get; set; }
        public int? AcaEspsur { get; set; }
        public string AcaMusout { get; set; }
        public int? AcaMusbat { get; set; }
        public int? AcaMusper { get; set; }
        public int? AcaMuscan { get; set; }
        public int? AcaMustec { get; set; }
        public int? AcaMuscor { get; set; }
        public int? AcaEspatl { get; set; }
        public string AcaProres { get; set; }
        public int? AcaDisanosn { get; set; }
        public DateTime? AcaProfim { get; set; }
        public DateTime? AcaProini { get; set; }
        public string AcaProcid { get; set; }
        public string AcaInt { get; set; }
        public string AcaApe { get; set; }
        public string AcaDisanores { get; set; }
        public string AcaDisferres { get; set; }
        public int? AcaDisfersn { get; set; }
        public int? AcaLining { get; set; }
        public string AcaLinoutd { get; set; }
        public int? AcaHab { get; set; }
        public int? AcaCar { get; set; }
        public int? AcaLinout { get; set; }
        public int? AcaLinesp { get; set; }
        public int? AcaProcon { get; set; }
        public string AcaProult { get; set; }
        public string AcaProcar { get; set; }
        public int? AcaUnisn { get; set; }
        public string AcaUnico { get; set; }
        public DateTime? AcaUnidt { get; set; }
        public int? CodFor { get; set; }
        public int? AcaEsphip { get; set; }
        public DateTime? AcaCon3 { get; set; }
        public string AcaHob { get; set; }
        public int? AcaEspvol { get; set; }
        public string AcaCur3 { get; set; }
        public string AcaEsc3 { get; set; }
        public DateTime? AcaCon2 { get; set; }
        public int? AcaEspnat { get; set; }
        public int? AcaEspten { get; set; }
        public int? AcaEspbas { get; set; }
        public int? AcaEspfut { get; set; }
        public int? AcaEsphan { get; set; }
        public string AcaEsc2 { get; set; }
        public string AcaEsc1 { get; set; }
        public DateTime? AcaCon1 { get; set; }
        public int? AcaVetfer { get; set; }
        public int? AcaVetagu { get; set; }
        public int? AcaVetsap { get; set; }
        public int? AcaVetsao { get; set; }
        public int? AcaVetitu { get; set; }
        public int? AcaVetfaz { get; set; }
        public int? AcaVetgua { get; set; }
        public string AcaAfa { get; set; }
        public int? CatmCod { get; set; }
        public DateTime? AcaIni { get; set; }
        public string AcaCarre { get; set; }
        public string AcaBan { get; set; }
        public string AcaAge { get; set; }
        public string AcaCco { get; set; }
        public string AcaBer { get; set; }
        public string AcaCal { get; set; }
        public string AcaUltc { get; set; }
        public string AcaCpf { get; set; }
        public string AcaContr { get; set; }
        public string AcaImp { get; set; }
        public string AcaPad { get; set; }
        public int? AcaOrd { get; set; }
        public decimal? AcaPes { get; set; }
        public decimal? AcaAlt { get; set; }
        public string AcaNeg { get; set; }
        public string AcaPer { get; set; }
        public string AcaRes { get; set; }
        public string DivEsc { get; set; }
        public string AcaTrg { get; set; }
        public int? ResCod { get; set; }
        public bool ResFin { get; set; }
        public string ObsFin { get; set; }
        public string ArqRg { get; set; }
    }
}
