using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class E080ser
    {
        public short CodEmp { get; set; }
        public string CodSer { get; set; }
        public string DesSer { get; set; }
        public string DesNfv { get; set; }
        public string CplSer { get; set; }
        public string CodFam { get; set; }
        public decimal? QtdPad { get; set; }
        public string UniMed { get; set; }
        public decimal? PreCpr { get; set; }
        public decimal? PreVen { get; set; }
        public decimal? PerDsc { get; set; }
        public decimal? PerIss { get; set; }
        public decimal? PerIns { get; set; }
        public decimal? PerIrf { get; set; }
        public decimal? PerCom { get; set; }
        public string CodTri { get; set; }
        public short? CodNtg { get; set; }
        public short CriRat { get; set; }
        public int? CtaRed { get; set; }
        public int? CtaRcr { get; set; }
        public int? CtaFdv { get; set; }
        public int? CtaFcr { get; set; }
        public string SitSer { get; set; }
        public decimal? NotFor { get; set; }
        public string ObsSer { get; set; }
        public string CodCcu { get; set; }
        public string CodClf { get; set; }
        public string CodStr { get; set; }
        public decimal? PerIpi { get; set; }
        public string RecIpi { get; set; }
        public string TemIcm { get; set; }
        public string CodTic { get; set; }
        public string CodTrd { get; set; }
        public string CodTst { get; set; }
        public string RecIcm { get; set; }
        public string RecPis { get; set; }
        public string TriPis { get; set; }
        public string TriCof { get; set; }
        public string CodFif { get; set; }
        public string CodFie { get; set; }
        public string CodFim { get; set; }
        public string RecCof { get; set; }
        public decimal? PerCsl { get; set; }
        public decimal? PerCof { get; set; }
        public decimal? PerPis { get; set; }
        public decimal? PerOur { get; set; }
        public string CodPin { get; set; }
        public long? CodPdv { get; set; }
        public string IndOct { get; set; }
        public string Indspr { get; set; }
        public long? Usuger { get; set; }
        public DateTime? Datger { get; set; }
        public int? Horger { get; set; }
        public long? Usualt { get; set; }
        public DateTime? Datalt { get; set; }
        public int? Horalt { get; set; }
        public string Codagt { get; set; }
        public string Serimp { get; set; }
        public string Varser { get; set; }
        public string Somips { get; set; }
        public string Somico { get; set; }
        public short? Conene { get; set; }
        public short? Conagu { get; set; }
        public short? Tiplig { get; set; }
        public short? Gruten { get; set; }
        public string Cstipi { get; set; }
        public string Cstpis { get; set; }
        public string Cstcof { get; set; }
        public string Tprpis { get; set; }
        public string Tprcof { get; set; }
        public string Tpripi { get; set; }
        public string Regtri { get; set; }
        public string Cstipc { get; set; }
        public string Cstpic { get; set; }
        public string Cstcoc { get; set; }
        public decimal? Qtdmlt { get; set; }
        public decimal? Qtdmin { get; set; }
        public decimal? Qtdmax { get; set; }
        public int? Natpis { get; set; }
        public int? Natcof { get; set; }
        public string Trinfs { get; set; }
        public decimal? Percit { get; set; }
        public string Catmnt { get; set; }
        public string Orimer { get; set; }
        public int? Codseg { get; set; }
        public short? Bascre { get; set; }
        public short? Codote { get; set; }
        public int? Codfil { get; set; }
        public string Codtpr { get; set; }
        public DateTime? Datini { get; set; }
        public decimal? Vlrini { get; set; }
        public decimal? Vlrfin { get; set; }
        public string Codagg { get; set; }
        public short? Codtge { get; set; }
        public short? Prztge { get; set; }
        public decimal? Vlrser { get; set; }
        public string Itefis { get; set; }
        public string Desfis { get; set; }
        public short? Idamin { get; set; }
        public short? Idamax { get; set; }
        public int? Fincrp { get; set; }
        public int? Fincdp { get; set; }
        public decimal? Perpim { get; set; }
        public decimal? Percim { get; set; }
        public int? Codtra { get; set; }
        public string Tiptge { get; set; }
        public string Parcom { get; set; }
        public string Codnbs { get; set; }
        public string Imoser { get; set; }
        public string Codbic { get; set; }
        public string Codexp { get; set; }
        public short? Tipser { get; set; }
        public short? Apoesp { get; set; }
        public decimal? Perdif { get; set; }
        public string Cstiss { get; set; }
        public string Codatv { get; set; }
        public decimal? Persen { get; set; }
        public string Codpri { get; set; }
        public string Codprc { get; set; }
        public string Codces { get; set; }
        public int? Coddfs { get; set; }
        public decimal? Perifp { get; set; }
        public int? Seqhas { get; set; }
        public short? Tipren { get; set; }
        public short? Fortri { get; set; }
        public short? Clacni { get; set; }
        public short? Tiputi { get; set; }
        public short? Natati { get; set; }
        public string Indm21 { get; set; }
        public int? Numcbo { get; set; }
        public short? Modpre { get; set; }
        public decimal? Perine { get; set; }
        public decimal? Perape { get; set; }
        public int? Ideren { get; set; }
        public string Natren { get; set; }
    }
}
