using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class E085cli
    {
        public int CodCli { get; set; }
        public string NomCli { get; set; }
        public string ApeCli { get; set; }
        public string MarCli { get; set; }
        public string SenCli { get; set; }
        public string TipCli { get; set; }
        public string TipMer { get; set; }
        public short? TipEmc { get; set; }
        public string CliCon { get; set; }
        public string CodRam { get; set; }
        public string InsEst { get; set; }
        public string InsMun { get; set; }
        public long? CgcCpf { get; set; }
        public int? CodGre { get; set; }
        public short? ZonFra { get; set; }
        public string CodSuf { get; set; }
        public string EndCli { get; set; }
        public string CplEnd { get; set; }
        public string CliPrx { get; set; }
        public string ZipCod { get; set; }
        public int? CepCli { get; set; }
        public int? CepIni { get; set; }
        public string BaiCli { get; set; }
        public string CidCli { get; set; }
        public string SigUfs { get; set; }
        public string CodPai { get; set; }
        public string TemEnt { get; set; }
        public string EndEnt { get; set; }
        public string CplEnt { get; set; }
        public int? CepEnt { get; set; }
        public int? IniEnt { get; set; }
        public string CidEnt { get; set; }
        public string EstEnt { get; set; }
        public string InsEnt { get; set; }
        public long? CgcEnt { get; set; }
        public string TemCob { get; set; }
        public string EndCob { get; set; }
        public string CplCob { get; set; }
        public int? CepCob { get; set; }
        public int? IniCob { get; set; }
        public string CidCob { get; set; }
        public string EstCob { get; set; }
        public long? CgcCob { get; set; }
        public string EntCor { get; set; }
        public string FonCli { get; set; }
        public string FonCl2 { get; set; }
        public string FonCl3 { get; set; }
        public string FonCl4 { get; set; }
        public string FonCl5 { get; set; }
        public string Faxcli { get; set; }
        public int? CxaPst { get; set; }
        public string IntNet { get; set; }
        public string CodRoe { get; set; }
        public short? SeqRoe { get; set; }
        public int? CodFor { get; set; }
        public int? CliRep { get; set; }
        public int? CliTra { get; set; }
        public long? UsuCad { get; set; }
        public DateTime? DatCad { get; set; }
        public DateTime? DatFim { get; set; }
        public int? HorCad { get; set; }
        public int? HorFim { get; set; }
        public DateTime? DatVct { get; set; }
        public DateTime? DatAtu { get; set; }
        public int? HorAtu { get; set; }
        public long? UsuAtu { get; set; }
        public short? QtdAtu { get; set; }
        public DateTime? DatIcv { get; set; }
        public string SitCli { get; set; }
        public int? CodMot { get; set; }
        public string BloCre { get; set; }
        public string ObsMot { get; set; }
        public long? UsuMot { get; set; }
        public DateTime? DatMot { get; set; }
        public int? HorMot { get; set; }
        public long? UsuOpe { get; set; }
        public string CodAma { get; set; }
        public string CodSab { get; set; }
        public string CodGal { get; set; }
        public string TriIcm { get; set; }
        public string TriIpi { get; set; }
        public string BaiEnt { get; set; }
        public string BaiCob { get; set; }
        public string CliFor { get; set; }
        public string IdeCli { get; set; }
        public string TriPis { get; set; }
        public string TriCof { get; set; }
        public short? IndExp { get; set; }
        public DateTime? DatPal { get; set; }
        public int? HorPal { get; set; }
        public string RetCof { get; set; }
        public string RetCsl { get; set; }
        public string RetPis { get; set; }
        public string RetOur { get; set; }
        public string CodSro { get; set; }
        public DateTime? DatSuf { get; set; }
        public int? CepFre { get; set; }
        public int? CodPdv { get; set; }
        public DateTime? DatPdv { get; set; }
        public int? HorPdv { get; set; }
        public string RetPro { get; set; }
        public string RetIrf { get; set; }
        public string LimRet { get; set; }
        public short? CodCnv { get; set; }
        public string CalFun { get; set; }
        public string EenCli { get; set; }
        public string EenEnt { get; set; }
        public string EenCob { get; set; }
        public decimal? Perain { get; set; }
        public string Nencli { get; set; }
        public string Nenent { get; set; }
        public string Nencob { get; set; }
        public short Tipace { get; set; }
        public string Emanfe { get; set; }
        public int? Insanp { get; set; }
        public string Indcoo { get; set; }
        public short? Regest { get; set; }
        public short? Codrtr { get; set; }
        public short? Natret { get; set; }
        public int? Natpis { get; set; }
        public int? Natcof { get; set; }
        public string Confin { get; set; }
        public string Numidf { get; set; }
        public short? Codmsg { get; set; }
        public short? Codms2 { get; set; }
        public short? Codms3 { get; set; }
        public short? Codms4 { get; set; }
        public string Calsen { get; set; }
        public short? Tipemp { get; set; }
        public short? Rotanx { get; set; }
        public long? Numanx { get; set; }
        public short? Natirp { get; set; }
        public short? Natcsl { get; set; }
        public int? Seqhas { get; set; }
        public string Entpaa { get; set; }
        public short? Clatri { get; set; }
        public DateTime? Datspc { get; set; }
        public string Cidspc { get; set; }
        public short? Infspc { get; set; }
        public long? Ususpc { get; set; }
        public string Msgpdv { get; set; }
        public short? Indnif { get; set; }
        public short? Tipvin { get; set; }
        public string Fonent { get; set; }
        public string Emaent { get; set; }
        public string Codtaf { get; set; }
        public string Zipent { get; set; }
        public string Vlrlat { get; set; }
        public string Vlrlon { get; set; }
        public string UsuDepide { get; set; }
        public string UsuBlqcli { get; set; }
        public string UsuBloqUsu { get; set; }
        public string UsuMotBloq { get; set; }
    }
}
