using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class E120ped
    {
        public short CodEmp { get; set; }
        public int CodFil { get; set; }
        public int NumPed { get; set; }
        public short? TipPed { get; set; }
        public short? PrcPed { get; set; }
        public string TnsPro { get; set; }
        public string TnsSer { get; set; }
        public DateTime DatEmi { get; set; }
        public int? HorEmi { get; set; }
        public DateTime? DatPrv { get; set; }
        public int? HorPrv { get; set; }
        public string ObsPed { get; set; }
        public int CodCli { get; set; }
        public short CatCli { get; set; }
        public short? QtdVpf { get; set; }
        public short? QtdMfp { get; set; }
        public string IndAgr { get; set; }
        public int? SeqEnt { get; set; }
        public int? SeqCob { get; set; }
        public int? SeqCto { get; set; }
        public string PedCli { get; set; }
        public string CodRoe { get; set; }
        public short? SeqRoe { get; set; }
        public int CodRep { get; set; }
        public string CodMoe { get; set; }
        public string CodMcp { get; set; }
        public DateTime? DatMfp { get; set; }
        public decimal? CotMfp { get; set; }
        public DateTime? DatMoe { get; set; }
        public decimal? CotMoe { get; set; }
        public string FecMoe { get; set; }
        public string CodFcr { get; set; }
        public DateTime? DatFcr { get; set; }
        public string CodCpg { get; set; }
        public string PgtAnt { get; set; }
        public short? CodFpg { get; set; }
        public decimal? QtdAbe { get; set; }
        public decimal? QtdAen { get; set; }
        public int? CodTra { get; set; }
        public int? CodRed { get; set; }
        public string CodVia { get; set; }
        public string PlaVei { get; set; }
        public decimal? VlrFum { get; set; }
        public decimal? QtdFre { get; set; }
        public int? ForFre { get; set; }
        public decimal? VlrFre { get; set; }
        public string CifFob { get; set; }
        public decimal? VlrSeg { get; set; }
        public decimal? VlrEmb { get; set; }
        public decimal? VlrEnc { get; set; }
        public decimal? VlrOut { get; set; }
        public decimal? VlrDar { get; set; }
        public decimal? VlrFrd { get; set; }
        public decimal? VlrOud { get; set; }
        public decimal? PerDs1 { get; set; }
        public decimal? PerDs2 { get; set; }
        public decimal? PerDs3 { get; set; }
        public decimal? PerDs4 { get; set; }
        public decimal? VlrBpr { get; set; }
        public decimal? VlrDpr { get; set; }
        public decimal? VlrBse { get; set; }
        public decimal? VlrDse { get; set; }
        public decimal? VlrDs1 { get; set; }
        public decimal? VlrDs2 { get; set; }
        public decimal? VlrDs3 { get; set; }
        public decimal? VlrDs4 { get; set; }
        public decimal? VlrOfe { get; set; }
        public decimal? VlrDzf { get; set; }
        public decimal? VlrBip { get; set; }
        public decimal? VlrIpi { get; set; }
        public decimal? VlrBic { get; set; }
        public decimal? VlrIcm { get; set; }
        public decimal? VlrBsi { get; set; }
        public decimal? VlrSic { get; set; }
        public decimal? VlrBsp { get; set; }
        public decimal? VlrStp { get; set; }
        public decimal? VlrBsc { get; set; }
        public decimal? VlrStc { get; set; }
        public decimal? VlrBis { get; set; }
        public decimal? VlrIss { get; set; }
        public decimal? VlrBir { get; set; }
        public decimal? VlrIrf { get; set; }
        public decimal? VlrBin { get; set; }
        public decimal? VlrIns { get; set; }
        public decimal? VlrBco { get; set; }
        public decimal? VlrCom { get; set; }
        public decimal? VlrLpr { get; set; }
        public decimal? VlrLse { get; set; }
        public decimal? VlrLou { get; set; }
        public decimal? VlrLiq { get; set; }
        public decimal? VlrFin { get; set; }
        public decimal? VlrAdt { get; set; }
        public decimal? QtdOri { get; set; }
        public decimal? VlrOri { get; set; }
        public string TemPar { get; set; }
        public string CodPor { get; set; }
        public string CodCrt { get; set; }
        public short SitPed { get; set; }
        public int? CodMot { get; set; }
        public string ObsMot { get; set; }
        public string PedBlo { get; set; }
        public long? UsuBlo { get; set; }
        public DateTime? DatBlo { get; set; }
        public int? HorBlo { get; set; }
        public string IndSig { get; set; }
        public short? VerCal { get; set; }
        public int? HorIni { get; set; }
        public int? HorFim { get; set; }
        public long? UsuGer { get; set; }
        public DateTime? DatGer { get; set; }
        public int? HorGer { get; set; }
        public decimal? PerFre { get; set; }
        public decimal? PerSeg { get; set; }
        public decimal? PerEmb { get; set; }
        public decimal? PerEnc { get; set; }
        public decimal? PerOut { get; set; }
        public long? CodSac { get; set; }
        public int? CodOpe { get; set; }
        public int? CodVen { get; set; }
        public int? PedPal { get; set; }
        public string AcePar { get; set; }
        public decimal? PerOf1 { get; set; }
        public decimal? PerOf2 { get; set; }
        public long? UsuFec { get; set; }
        public DateTime? DatFec { get; set; }
        public int? HorFec { get; set; }
        public int? CliRel { get; set; }
        public decimal? VlrBcl { get; set; }
        public decimal? VlrCsl { get; set; }
        public decimal? VlrBpt { get; set; }
        public decimal? VlrPit { get; set; }
        public decimal? VlrBct { get; set; }
        public decimal? VlrCrt { get; set; }
        public decimal? VlrBor { get; set; }
        public decimal? VlrOur { get; set; }
        public string CodMar { get; set; }
        public string CodSro { get; set; }
        public int? FilFat { get; set; }
        public short? CodCdi { get; set; }
        public string CodLip { get; set; }
        public int? CepFre { get; set; }
        public decimal? VlrRis { get; set; }
        public string AnaEmb { get; set; }
        public string NumEmp { get; set; }
        public int? QtdAne { get; set; }
        public DateTime? DatAge { get; set; }
        public int? FilNco { get; set; }
        public string SnfNco { get; set; }
        public int? NumNco { get; set; }
        public short? Expwms { get; set; }
        public decimal? Vlrbpf { get; set; }
        public decimal? Vlrpif { get; set; }
        public decimal? Vlrbcf { get; set; }
        public decimal? Vlrcff { get; set; }
        public int? Codapc { get; set; }
        public string Somfre { get; set; }
        public short? Qtditp { get; set; }
        public short? Qtdits { get; set; }
        public decimal? Perds5 { get; set; }
        public decimal? Vlrds5 { get; set; }
        public short? Rotanx { get; set; }
        public long? Numanx { get; set; }
        public long? Numnsu { get; set; }
        public DateTime? Datnsu { get; set; }
        public int? Hornsu { get; set; }
        public short? Indexp { get; set; }
        public short? Fatped { get; set; }
        public decimal? Qtdbpf { get; set; }
        public decimal? Qtdbcf { get; set; }
        public decimal? Qtdbip { get; set; }
        public long? Numces { get; set; }
        public string Vencal { get; set; }
        public string Desdef { get; set; }
        public string Anovei { get; set; }
        public string Numren { get; set; }
        public string Desmod { get; set; }
        public short? Tipdav { get; set; }
        public decimal? Vlrecf { get; set; }
        public decimal? Perecf { get; set; }
        public string Temava { get; set; }
        public string Codtab { get; set; }
        public string Senapr { get; set; }
        public long? Usuapr { get; set; }
        public DateTime? Datapr { get; set; }
        public int? Horapr { get; set; }
        public short? Sitpac { get; set; }
        public long? Usupac { get; set; }
        public short? Qtdpac { get; set; }
        public string Codsaf { get; set; }
        public DateTime? Datpre { get; set; }
        public string Indpre { get; set; }
        public string Curmil { get; set; }
        public decimal? Basidf { get; set; }
        public decimal? Vlridf { get; set; }
        public short? Sitmes { get; set; }
        public decimal? Vlricd { get; set; }
        public int? Motwms { get; set; }
        public short? Tipent { get; set; }
        public string Forent { get; set; }
        public int? Seqhas { get; set; }
        public short? Eqfimp { get; set; }
        public int? Cooimp { get; set; }
        public int? Croecf { get; set; }
        public decimal? Vlrtot { get; set; }
        public string Numint { get; set; }
        public string Ideevt { get; set; }
        public decimal? Vlrior { get; set; }
        public decimal? Vlrbde { get; set; }
        public decimal? Vlride { get; set; }
        public decimal? Basfcp { get; set; }
        public decimal? Vlrfcp { get; set; }
        public decimal? Bstfcp { get; set; }
        public decimal? Vstfcp { get; set; }
        public decimal? Icmbfc { get; set; }
        public decimal? Icmvfc { get; set; }
        public int? Cepini { get; set; }
        public int? Cepfim { get; set; }
        public string UsuCodpai { get; set; }
        public string UsuCodped { get; set; }
    }
}
