using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class E120isp
    {
        public short CodEmp { get; set; }
        public int CodFil { get; set; }
        public int NumPed { get; set; }
        public short SeqIsp { get; set; }
        public string TnsSer { get; set; }
        public string CodSer { get; set; }
        public string CplIsp { get; set; }
        public string CodFam { get; set; }
        public string CodTri { get; set; }
        public int? NumCad { get; set; }
        public decimal QtdPed { get; set; }
        public decimal? QtdRea { get; set; }
        public decimal? QtdFat { get; set; }
        public decimal? QtdCan { get; set; }
        public decimal? QtdAbe { get; set; }
        public string UniMed { get; set; }
        public string CodMcp { get; set; }
        public DateTime? DatMfp { get; set; }
        public decimal? CotMfp { get; set; }
        public DateTime? DatMoe { get; set; }
        public decimal? CotMoe { get; set; }
        public string FecMoe { get; set; }
        public DateTime DatEnt { get; set; }
        public string CodTpr { get; set; }
        public decimal PreUni { get; set; }
        public string CodMoe { get; set; }
        public decimal? PerDsc { get; set; }
        public decimal? PerIss { get; set; }
        public decimal? PerIrf { get; set; }
        public decimal? PerIns { get; set; }
        public decimal? PerCom { get; set; }
        public int? NumPrj { get; set; }
        public short? CodFpj { get; set; }
        public int? CtaFin { get; set; }
        public int? CtaRed { get; set; }
        public string CodCcu { get; set; }
        public decimal? VlrEnc { get; set; }
        public decimal? VlrOut { get; set; }
        public decimal? VlrDar { get; set; }
        public decimal? VlrBru { get; set; }
        public decimal? VlrDsc { get; set; }
        public decimal? VlrDs1 { get; set; }
        public decimal? VlrDs2 { get; set; }
        public decimal? VlrDs3 { get; set; }
        public decimal? VlrDs4 { get; set; }
        public decimal? VlrBis { get; set; }
        public decimal? VlrIss { get; set; }
        public decimal? VlrBir { get; set; }
        public decimal? VlrIrf { get; set; }
        public decimal? VlrBin { get; set; }
        public decimal? VlrIns { get; set; }
        public decimal? VlrBco { get; set; }
        public decimal? VlrCom { get; set; }
        public decimal? VlrLse { get; set; }
        public decimal? VlrLou { get; set; }
        public decimal? VlrLiq { get; set; }
        public decimal? VlrFin { get; set; }
        public short SitIsp { get; set; }
        public int? CodMot { get; set; }
        public string ObsMot { get; set; }
        public int? NumCtr { get; set; }
        public DateTime? DatCpt { get; set; }
        public short? SeqCvs { get; set; }
        public string PedCli { get; set; }
        public string SeqPcl { get; set; }
        public long? UsuGer { get; set; }
        public DateTime? DatGer { get; set; }
        public int? HorGer { get; set; }
        public string ObsIsp { get; set; }
        public int? FilOcp { get; set; }
        public int? NumOcp { get; set; }
        public short? SeqIso { get; set; }
        public string CodTic { get; set; }
        public string CodTrd { get; set; }
        public string CodTst { get; set; }
        public decimal? PerIpi { get; set; }
        public decimal? PerIcm { get; set; }
        public decimal? VlrDzf { get; set; }
        public decimal? VlrBip { get; set; }
        public decimal? VlrIpi { get; set; }
        public decimal? VlrBic { get; set; }
        public decimal? VlrIcm { get; set; }
        public decimal? VlrBsi { get; set; }
        public decimal? VlrIcs { get; set; }
        public decimal? VlrBct { get; set; }
        public decimal? VlrCrt { get; set; }
        public decimal? PerCrt { get; set; }
        public decimal? VlrBpt { get; set; }
        public decimal? VlrPit { get; set; }
        public decimal? PerPit { get; set; }
        public decimal? VlrBcl { get; set; }
        public decimal? VlrCsl { get; set; }
        public decimal? PerCsl { get; set; }
        public decimal? VlrBor { get; set; }
        public decimal? VlrOur { get; set; }
        public decimal? PerOur { get; set; }
        public decimal? PerDs1 { get; set; }
        public decimal? PerDs2 { get; set; }
        public decimal? PerDs3 { get; set; }
        public decimal? PerDs4 { get; set; }
        public decimal? VlrRis { get; set; }
        public short? Gernec { get; set; }
        public short? Empocp { get; set; }
        public decimal? Vlrbpf { get; set; }
        public decimal? Perpif { get; set; }
        public decimal? Vlrpif { get; set; }
        public decimal? Vlrbcf { get; set; }
        public decimal? Percff { get; set; }
        public decimal? Vlrcff { get; set; }
        public decimal? Perds5 { get; set; }
        public decimal? Vlrds5 { get; set; }
        public decimal? Qtdbip { get; set; }
        public decimal? Aliipi { get; set; }
        public decimal? Qtdbpf { get; set; }
        public decimal? Alipif { get; set; }
        public decimal? Qtdbcf { get; set; }
        public decimal? Alicff { get; set; }
        public int? Filctr { get; set; }
        public int? Ctrcvs { get; set; }
        public short? Seqctr { get; set; }
        public DateTime? Cptcvs { get; set; }
        public int? Filref { get; set; }
        public int? Pedref { get; set; }
        public short? Seqref { get; set; }
        public decimal? Vlrpfm { get; set; }
        public string Varser { get; set; }
        public string Senapr { get; set; }
        public short? Empfre { get; set; }
        public string Tabfre { get; set; }
        public DateTime? Datini { get; set; }
        public int? Locent { get; set; }
        public int? Filfre { get; set; }
        public int? Codrep { get; set; }
        public short? Seqflc { get; set; }
        public decimal? Permgc { get; set; }
        public decimal? Perjur { get; set; }
        public decimal? Vlroud { get; set; }
        public decimal? Perdif { get; set; }
        public decimal? Basidf { get; set; }
        public decimal? Peridf { get; set; }
        public decimal? Vlridf { get; set; }
        public string Codstr { get; set; }
        public int? Filnco { get; set; }
        public string Snfnco { get; set; }
        public int? Numnco { get; set; }
        public short? Seqnco { get; set; }
        public short? Motdes { get; set; }
        public decimal? Vlricd { get; set; }
        public decimal? Icmaor { get; set; }
        public decimal? Icmvor { get; set; }
        public decimal? Icmade { get; set; }
        public decimal? Icmvde { get; set; }
        public decimal? Icmbde { get; set; }
        public decimal? Icmafc { get; set; }
        public decimal? Icmvfc { get; set; }
        public int? Filnfv { get; set; }
        public string Snfnfv { get; set; }
        public int? Numnfv { get; set; }
        public short? Seqipv { get; set; }
        public int? Seqhas { get; set; }
        public DateTime? Datalt { get; set; }
        public int? Horalt { get; set; }
        public long? Usualt { get; set; }
        public decimal? Vlrtot { get; set; }
        public string Itecan { get; set; }
        public decimal? Dscvar { get; set; }
        public decimal? Pdsvar { get; set; }
        public string Numint { get; set; }
        public decimal? Icmbfc { get; set; }
        public decimal? Basfcp { get; set; }
        public decimal? Alifcp { get; set; }
        public decimal? Vlrfcp { get; set; }
        public decimal? Bstfcp { get; set; }
        public decimal? Astfcp { get; set; }
        public decimal? Vstfcp { get; set; }
    }
}
