using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class E301mcr
    {
        public short CodEmp { get; set; }
        public int CodFil { get; set; }
        public string NumTit { get; set; }
        public string CodTpt { get; set; }
        public short SeqMov { get; set; }
        public string CodTns { get; set; }
        public DateTime DatMov { get; set; }
        public string ObsMcr { get; set; }
        public string NumDoc { get; set; }
        public DateTime? VctPro { get; set; }
        public string ProJrs { get; set; }
        public decimal? VlrAbe { get; set; }
        public string CodFrj { get; set; }
        public decimal? CotFrj { get; set; }
        public DateTime? DatPgt { get; set; }
        public short? CodFpg { get; set; }
        public decimal? CotMcr { get; set; }
        public short? DiaAtr { get; set; }
        public short? DiaJrs { get; set; }
        public string RecJoa { get; set; }
        public string RecJod { get; set; }
        public DateTime? DatLib { get; set; }
        public decimal VlrMov { get; set; }
        public decimal? VlrDsc { get; set; }
        public decimal? VlrOde { get; set; }
        public decimal? VlrJrs { get; set; }
        public decimal? VlrMul { get; set; }
        public decimal? VlrEnc { get; set; }
        public decimal? VlrCor { get; set; }
        public decimal? VlrOac { get; set; }
        public decimal? VlrPis { get; set; }
        public decimal? VlrBpr { get; set; }
        public decimal? VlrCof { get; set; }
        public decimal? VlrBcr { get; set; }
        public decimal? VlrPit { get; set; }
        public decimal? VlrBpt { get; set; }
        public decimal? VlrOpt { get; set; }
        public decimal? VlrCrt { get; set; }
        public decimal? VlrBct { get; set; }
        public decimal? VlrOct { get; set; }
        public decimal? VlrCsl { get; set; }
        public decimal? VlrBcl { get; set; }
        public decimal? VlrOcl { get; set; }
        public decimal? VlrOur { get; set; }
        public decimal? VlrBor { get; set; }
        public decimal? VlrOor { get; set; }
        public decimal? VlrLiq { get; set; }
        public decimal? VlrBco { get; set; }
        public decimal? VlrCom { get; set; }
        public decimal? PerJrs { get; set; }
        public DateTime? UltPgt { get; set; }
        public DateTime? CjmAnt { get; set; }
        public decimal? JrsCal { get; set; }
        public string JrsPro { get; set; }
        public string CodPor { get; set; }
        public string CodCrt { get; set; }
        public string PorAnt { get; set; }
        public string CrtAnt { get; set; }
        public int? NumPrj { get; set; }
        public short? CodFpj { get; set; }
        public int? CtaFin { get; set; }
        public int? CtaRed { get; set; }
        public string CodCcu { get; set; }
        public short? EmpCco { get; set; }
        public string NumCco { get; set; }
        public DateTime? DatCco { get; set; }
        public int? SeqCco { get; set; }
        public int? FilRlc { get; set; }
        public string NumRlc { get; set; }
        public string TptRlc { get; set; }
        public int? ForRlc { get; set; }
        public short? SeqRlc { get; set; }
        public short? SeqMcp { get; set; }
        public string IndVcr { get; set; }
        public string LctFin { get; set; }
        public short? TipCof { get; set; }
        public int? NumLot { get; set; }
        public long? UsuGer { get; set; }
        public DateTime? DatGer { get; set; }
        public int? HorGer { get; set; }
        public int? Lotbai { get; set; }
        public short? Indexp { get; set; }
        public int? Filfix { get; set; }
        public int? Numfix { get; set; }
        public int? Lotbfi { get; set; }
        public string Recmoa { get; set; }
        public string Intimp { get; set; }
        public string Intdif { get; set; }
        public decimal? Vlrirf { get; set; }
        public decimal? Vlrbir { get; set; }
        public decimal? Vlroir { get; set; }
        public decimal? Vlrint { get; set; }
        public string Chvlot { get; set; }
        public int? Seqlba { get; set; }
        public int? Filori { get; set; }
        public DateTime? Reaanb { get; set; }
        public short? Numpdv { get; set; }
        public decimal? Pitcal { get; set; }
        public decimal? Crtcal { get; set; }
        public decimal? Cslcal { get; set; }
        public decimal? Ourcal { get; set; }
        public int? Numctr { get; set; }
        public short? Toldsc { get; set; }
        public short? Toljrs { get; set; }
        public short? Tolmul { get; set; }
        public decimal? Irfcal { get; set; }
    }
}
