using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class E301tcr
    {
        public short CodEmp { get; set; }
        public int CodFil { get; set; }
        public string NumTit { get; set; }
        public string CodTpt { get; set; }
        public string CodTns { get; set; }
        public short? CodNtg { get; set; }
        public string SitTit { get; set; }
        public DateTime DatEnt { get; set; }
        public DateTime DatEmi { get; set; }
        public int CodCli { get; set; }
        public long? CodSac { get; set; }
        public int CodRep { get; set; }
        public string CodCrp { get; set; }
        public string ObsTcr { get; set; }
        public DateTime VctOri { get; set; }
        public decimal VlrOri { get; set; }
        public short? CodFpg { get; set; }
        public DateTime VctPro { get; set; }
        public string ProJrs { get; set; }
        public string CodMpt { get; set; }
        public DateTime DatPpt { get; set; }
        public decimal? VlrAbe { get; set; }
        public string CodMoe { get; set; }
        public decimal? CotEmi { get; set; }
        public string CodFrj { get; set; }
        public decimal? CotFrj { get; set; }
        public decimal? PerCom { get; set; }
        public decimal? ComRec { get; set; }
        public decimal? VlrBco { get; set; }
        public decimal? VlrCom { get; set; }
        public DateTime? DatDsc { get; set; }
        public short? TolDsc { get; set; }
        public decimal? PerDsc { get; set; }
        public decimal? VlrDsc { get; set; }
        public string AntDsc { get; set; }
        public decimal? PerJrs { get; set; }
        public string TipJrs { get; set; }
        public decimal? JrsDia { get; set; }
        public short? TolJrs { get; set; }
        public DateTime DatCjm { get; set; }
        public decimal? PerMul { get; set; }
        public short? TolMul { get; set; }
        public string CheBan { get; set; }
        public string CheAge { get; set; }
        public string CheCta { get; set; }
        public string CheNum { get; set; }
        public string CodPor { get; set; }
        public string CodCrt { get; set; }
        public string TitBan { get; set; }
        public int? NumArb { get; set; }
        public string CodOcr { get; set; }
        public string CodIn1 { get; set; }
        public string CodIn2 { get; set; }
        public string PorAnt { get; set; }
        public string CrtAnt { get; set; }
        public DateTime? UltPgt { get; set; }
        public DateTime? DatNeg { get; set; }
        public decimal? JrsNeg { get; set; }
        public decimal? MulNeg { get; set; }
        public decimal? DscNeg { get; set; }
        public decimal? OutNeg { get; set; }
        public long? UsuNeg { get; set; }
        public string CpgNeg { get; set; }
        public decimal? TaxNeg { get; set; }
        public decimal? VlrDca { get; set; }
        public decimal? VlrDcb { get; set; }
        public decimal? VlrOud { get; set; }
        public short? NotDeb { get; set; }
        public int? NumPrj { get; set; }
        public short? CodFpj { get; set; }
        public int? CtaFin { get; set; }
        public int? CtaRed { get; set; }
        public string CodCcu { get; set; }
        public short? QtdDup { get; set; }
        public short? QtdBlo { get; set; }
        public DateTime? DatUcm { get; set; }
        public decimal? CotUcm { get; set; }
        public int? FilNfv { get; set; }
        public string CodSnf { get; set; }
        public int? NumNfv { get; set; }
        public int? FilCtr { get; set; }
        public int? NumCtr { get; set; }
        public short? SeqImo { get; set; }
        public int? FilNff { get; set; }
        public int? NumNff { get; set; }
        public int? FilPed { get; set; }
        public int? NumPed { get; set; }
        public int? FilNfc { get; set; }
        public int? ForNfc { get; set; }
        public int? NumNfc { get; set; }
        public string SnfNfc { get; set; }
        public int? FilNdb { get; set; }
        public string NumNdb { get; set; }
        public string TptNdb { get; set; }
        public string TipEfe { get; set; }
        public string TnsPre { get; set; }
        public DateTime? DatPre { get; set; }
        public decimal? VlrPre { get; set; }
        public string CodBar { get; set; }
        public int? NumEco { get; set; }
        public string NumAce { get; set; }
        public long? UsuGer { get; set; }
        public DateTime? DatGer { get; set; }
        public int? HorGer { get; set; }
        public int? FilCcr { get; set; }
        public int? NumCcr { get; set; }
        public decimal? VlrOrm { get; set; }
        public decimal? CotNeg { get; set; }
        public string Cattef { get; set; }
        public string Nsutef { get; set; }
        public short? Rotsap { get; set; }
        public int? Ctrfre { get; set; }
        public int? Ctrnre { get; set; }
        public int? Pedfre { get; set; }
        public int? Pednre { get; set; }
        public short? Sitpef { get; set; }
        public string Prddsc { get; set; }
        public long? Ususit { get; set; }
        public long? Numdfs { get; set; }
        public int? Numcfi { get; set; }
        public string Catext { get; set; }
        public short? Codope { get; set; }
        public string Carcov { get; set; }
        public string Carpre { get; set; }
        public short? Codcnv { get; set; }
        public short? Codequ { get; set; }
        public string Sitant { get; set; }
        public short? Empcto { get; set; }
        public short? Codpco { get; set; }
        public int? Filcto { get; set; }
        public DateTime? Cptpco { get; set; }
        public string Loctit { get; set; }
        public string Indadc { get; set; }
        public int? Numpvc { get; set; }
        public int? Numrvc { get; set; }
        public short? Parcar { get; set; }
        public int? Croecf { get; set; }
        public decimal? Dscpon { get; set; }
        public short? Libccl { get; set; }
        public string Jurven { get; set; }
        public decimal? Vlrint { get; set; }
        public int? Filpfi { get; set; }
        public string Numpfi { get; set; }
        public int? Seqcob { get; set; }
        public short? Codfin { get; set; }
        public int? Filagr { get; set; }
        public DateTime? Datagr { get; set; }
        public long? Chvagr { get; set; }
        public DateTime? Reatcr { get; set; }
        public string Indtcf { get; set; }
        public string Nummal { get; set; }
        public int? Orisub { get; set; }
        public string Ctpneg { get; set; }
        public string Bancar { get; set; }
        public string Nsuhst { get; set; }
        public string Intre2 { get; set; }
        public string Intre4 { get; set; }
        public decimal? Vlrmoe { get; set; }
        public string Conlcd { get; set; }
        public int? UsuPedido { get; set; }
    }
}
