using System;
using System.Collections.Generic;

namespace Fichas.SoaContext
{
    public partial class TbCadRetornoConteudo
    {
        public long CodRetornoConteudo { get; set; }
        public long? CodRetorno { get; set; }
        public string DesRegistro { get; set; }
        public string CtAgencia { get; set; }
        public string CtDvAgencia { get; set; }
        public string CtCcCedente { get; set; }
        public string CtDvCcCedente { get; set; }
        public string CtConvenio { get; set; }
        public string CtControle { get; set; }
        public string CtNossoNumero { get; set; }
        public string CtTipoCobranca { get; set; }
        public string CtTipoCobrancaCmd72 { get; set; }
        public string CtDiasCalculo { get; set; }
        public string CtNatureza { get; set; }
        public string CtUsoBanco1 { get; set; }
        public string CtVariacaoCarteira { get; set; }
        public string CtContaCaucao { get; set; }
        public string CtUsoBanco2 { get; set; }
        public string CtUsoBanco3 { get; set; }
        public string CtTaxaDesconto { get; set; }
        public string CtTaxaIof { get; set; }
        public string CtCarteira { get; set; }
        public string CtComando { get; set; }
        public string CtDataPagamento { get; set; }
        public string CtNumTitulo { get; set; }
        public string CtConfirmacao { get; set; }
        public string CtDataVencimento { get; set; }
        public string CtValorTitulo { get; set; }
        public string CtCodBanco { get; set; }
        public string CtAgenciaReceb { get; set; }
        public string CtDvAgenciaReceb { get; set; }
        public string CtEspecie { get; set; }
        public string CtDataCredito { get; set; }
        public string CtValorTarifa { get; set; }
        public string CtOutrasDespesas { get; set; }
        public string CtJurosDesconto { get; set; }
        public string CtIofDesconto { get; set; }
        public string CtValorAbatimento { get; set; }
        public string CtDescontoConcedido { get; set; }
        public string CtValorPagamento { get; set; }
        public string CtJurosMora { get; set; }
        public string CtOutrosRecebimentos { get; set; }
        public string CtAbatimentoNAprov { get; set; }
        public string CtValorLancamento { get; set; }
        public string CtIndicativoDc { get; set; }
        public string CtIndicadorValor { get; set; }
        public string CtValorAjuste { get; set; }
        public string CtLiquidacaoParcial { get; set; }
        public string CtCanalPagTitulo { get; set; }
        public string CtBancoCredito1 { get; set; }
        public string CtCamaraCompensacao1 { get; set; }
        public string CtPreAgCredito1 { get; set; }
        public string CtDvAgCredito1 { get; set; }
        public string CtContaCredito1 { get; set; }
        public string CtDvContaCredito1 { get; set; }
        public string CtNomeFavorecido1 { get; set; }
        public string CtValInfoPartilha1 { get; set; }
        public string CtValEfetPartilha1 { get; set; }
        public string CtBancoCredito2 { get; set; }
        public string CtCamaraCompensacao2 { get; set; }
        public string CtPreAgCredito2 { get; set; }
        public string CtDvAgCredito2 { get; set; }
        public string CtContaCredito2 { get; set; }
        public string CtDvContaCredito2 { get; set; }
        public string CtNomeFavorecido2 { get; set; }
        public string CtValInfoPartilha2 { get; set; }
        public string CtValEfetPartilha2 { get; set; }
        public string CtBancoCredito3 { get; set; }
        public string CtCamaraCompensacao3 { get; set; }
        public string CtPreAgCredito3 { get; set; }
        public string CtDvAgCredito3 { get; set; }
        public string CtContaCredito3 { get; set; }
        public string CtDvContaCredito3 { get; set; }
        public string CtNomeFavorecido3 { get; set; }
        public string CtValInfoPartilha3 { get; set; }
        public string CtValEfetPartilha3 { get; set; }
        public string CtBancoCredito4 { get; set; }
        public string CtCamaraCompensacao4 { get; set; }
        public string CtPreAgCredito4 { get; set; }
        public string CtDvAgCredito4 { get; set; }
        public string CtContaCredito4 { get; set; }
        public string CtDvContaCredito4 { get; set; }
        public string CtNomeFavorecido4 { get; set; }
        public string CtValInfoPartilha4 { get; set; }
        public string CtValEfetPartilha4 { get; set; }
        public string CtTipoDocFavorecido1 { get; set; }
        public string CtNumDocFavorecido1 { get; set; }
        public string CtTipoDocFavorecido2 { get; set; }
        public string CtNumDocFavorecido2 { get; set; }
        public string CtTipoDocFavorecido3 { get; set; }
        public string CtNumDocFavorecido3 { get; set; }
        public string CtTipoDocFavorecido4 { get; set; }
        public string CtNumDocFavorecido4 { get; set; }
        public string CtDvNossoNumero { get; set; }
        public string CtNumOperacaoBbvendor { get; set; }
        public string CtDataBbvendor { get; set; }
        public string CtTxJurosVendedor { get; set; }
        public string CtTxJurosComprador { get; set; }
        public string CtValorTituloVenc { get; set; }
        public string CtValorOriginalVenda { get; set; }
        public string CtValorEncargComp { get; set; }
        public string CtValorIofFinanciado { get; set; }
        public string CtValorAcumuladoAbat { get; set; }
        public string CtIndEpocaEqualizacao { get; set; }
        public string CtIndNaturEqualizacao { get; set; }
        public string CtValorEqualizacao { get; set; }
        public string CtValorJurosProrrogacao { get; set; }
        public string CtValorIofProrrogacao { get; set; }
        public string CtValorIofPeriodoatraso { get; set; }
        public string CtNomeComprador { get; set; }
        public string CtCodTipoDocComprador { get; set; }
        public string CtNumDocumentoComprador { get; set; }
        public string CtConversaoCnab240 { get; set; }
        public string CtNossonumero17posicoes { get; set; }
        public string CtNovoValorTitulo { get; set; }
        public string CtValorEqualizacaoEst { get; set; }
        public string CtValorNovaEqualizacao { get; set; }
        public string CtValorDifEqualizacao { get; set; }
        public string CtIndCredDeb { get; set; }
        public string CtIndNatEqualizacao25 { get; set; }
        public string CtIndNatEqualizacao26 { get; set; }
        public string CtValorIofNfinanciado { get; set; }
        public string CtValorComissaoPerm { get; set; }
        public string CtTipoServico { get; set; }
        public string CtEmails { get; set; }
        public string CtValorCheque { get; set; }
        public string CtPrazobloqCheque { get; set; }
        public string CtMotivoDevolucao { get; set; }
        public string CtTrilhaCheque { get; set; }
        public string CtTipoCaptura { get; set; }
        public string CtSequencialReg { get; set; }

        public virtual TbCadRetorno CodRetornoNavigation { get; set; }
    }
}
